version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    labels:
      - "⬆️ deps"
    commit-message:
      prefix: "⬆️ "
    groups:
      actions:
        patterns: ["*"]

  # this doesn't work yet: https://github.com/astral-sh/uv/issues/2512
  - package-ecosystem: uv
    versioning-strategy: increase
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-type: "all"
    labels:
      - "⬆️ deps"
    commit-message:
      prefix: "⬆️ "
    groups:
      actions:
        patterns: ["*"]
