version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    labels:
      - "⬆️ deps"
    commit-message:
      prefix: "⬆️ "
    groups:
      actions:
        patterns: ["*"]

  # this doesn't work (yet?)
  - package-ecosystem: uv
    versioning-strategy: increase
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    labels:
      - "⬆️ deps"
    commit-message:
      prefix: "⬆️ "
    groups:
      actions:
        patterns: ["*"]
