name: CI
permissions: read-all

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb

      - name: Install the project
        run: uv sync --locked --group test

      - name: Run lefthook hooks
        run: uv run --frozen lefthook run pre-commit

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [format]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --group test

      - name: Test package
        run: >-
          uv run --frozen pytest
          --cov --cov-report=xml --cov-report=term --durations=20
          src docs tests 

      - name: Upload coverage report
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check_oldest:
    name: Check Oldest Dependencies
    runs-on: ${{ matrix.runs-on }}
    needs: [format]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --locked --group test --resolution lowest-direct

      - name: Test package
        run: >-
          uv run --frozen pytest
          --cov --cov-report=xml --cov-report=term --durations=20
          src docs tests

      - name: Upload coverage report
        uses: codecov/codecov-action@v18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
